version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file: 
      - ./env/.env
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_USER_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db_data:/var/lib/mysql
    networks:
      challenge:
        ipv4_address: 173.40.0.7
  web:
    env_file: 
      - ./env/.env
    build:
      context: .
    ports:
      - '8080:8080'
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
      - ./env:/env
    networks:
      challenge:
        ipv4_address: 173.40.0.8
volumes:
  db_data:

networks:
  challenge:
    driver: bridge
    ipam:
      config:
        - subnet: 173.40.0.0/16
