version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ulimits:
      nproc: 65535
      nofile:
          soft: 20000
          hard: 40000
    env_file: 
      - ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_USER_PASSWORD=$MYSQLDB_USER_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db_data:/var/lib/mysql
    networks:
      challenge:
        ipv4_address: 173.40.0.7
  web:
    env_file: 
      - ./.env
    build:
      context: .
    ports:
      - '$NODE_LOCAL_PORT:$NODE_DOCKER_PORT'
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
      - .:/env
    networks:
      challenge:
        ipv4_address: 173.40.0.8
volumes:
  db_data:

networks:
  challenge:
    driver: bridge
    ipam:
      config:
        - subnet: 173.40.0.0/16
